dependencies:
- python=3.10
- pip 
- pandas 
- anaconda::requests
- pytest 
- conda-forge::jupyter
- conda-forge::notebook
- conda-forge::black=22.3.0
- pip:
  - prospector[with_everything]==1.7.7
  - python-dotenv
  - pytest-dotenv
  - -e .
