name: dsp_client
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip 
  - pandas=2.1.4
  - pytest=7.4.*
  - jupyter
  - notebook
  - black=22.3.0
  - openpyxl
  - prospector=1.7.7
  - python-dotenv
  - pytest-dotenv
